# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BppMobileTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '9.3'

  # Pods for Rosie
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'

  target 'BppMobileTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BppMobileTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
